# Generated by Django 5.2.3 on 2025-06-19 00:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgrupacionMusical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("razon_social", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="CantoVallenato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["titulo"],
            },
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(blank=True, max_length=100, null=True)),
                ("apellidos", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "formacion_academica",
                    models.CharField(
                        choices=[
                            ("0", "Ninguno"),
                            ("1", "Primaria"),
                            ("2", "Secundaria"),
                            ("3", "Pregrado"),
                            ("4", "Posgrado"),
                        ],
                        default="1",
                        max_length=1,
                    ),
                ),
                ("nombre_artistico", models.CharField(max_length=100)),
                ("anio_nace", models.IntegerField(blank=True, null=True)),
                ("lugar_nace", models.CharField(blank=True, max_length=50, null=True)),
                ("lugar_muere", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="imagenes/"),
                ),
            ],
            options={
                "ordering": ["nombre_artistico"],
            },
        ),
        migrations.CreateModel(
            name="RitmoVallenato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("compositor", "Compositor"),
                            ("acordeonero", "Acordeonero"),
                            ("cantante", "Cantante"),
                            ("corista", "Corista"),
                            ("cajero", "Cajero"),
                            ("guacharaquero", "Guacharaquero"),
                            ("guitarrista", "Guitarrista"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AlbumVallenato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("anio_graba", models.CharField(blank=True, null=True)),
                (
                    "isbn",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        null=True,
                        unique=True,
                        verbose_name="ISBN",
                    ),
                ),
                (
                    "agrupacion",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cantovallenato.agrupacionmusical",
                    ),
                ),
                (
                    "cancion",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cantovallenato.cantovallenato",
                    ),
                ),
            ],
            options={
                "ordering": ["anio_graba"],
            },
        ),
        migrations.AddField(
            model_name="cantovallenato",
            name="compositor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cantovallenato.persona",
            ),
        ),
        migrations.AddField(
            model_name="agrupacionmusical",
            name="acordeonero",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agrupaciones_acordeonero",
                to="cantovallenato.persona",
            ),
        ),
        migrations.AddField(
            model_name="agrupacionmusical",
            name="cajero",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agrupaciones_cajero",
                to="cantovallenato.persona",
            ),
        ),
        migrations.AddField(
            model_name="agrupacionmusical",
            name="corista_dos",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agrupaciones_corista_dos",
                to="cantovallenato.persona",
            ),
        ),
        migrations.AddField(
            model_name="agrupacionmusical",
            name="corista_uno",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agrupaciones_corista_uno",
                to="cantovallenato.persona",
            ),
        ),
        migrations.AddField(
            model_name="agrupacionmusical",
            name="guacharaquero",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agrupaciones_guacharaquero",
                to="cantovallenato.persona",
            ),
        ),
        migrations.AddField(
            model_name="agrupacionmusical",
            name="guitarrista",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agrupaciones_guitarrista",
                to="cantovallenato.persona",
            ),
        ),
        migrations.AddField(
            model_name="agrupacionmusical",
            name="voz_principal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agrupaciones_voz_principal",
                to="cantovallenato.persona",
            ),
        ),
        migrations.AddField(
            model_name="cantovallenato",
            name="ritmo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cantovallenato.ritmovallenato",
            ),
        ),
        migrations.AddField(
            model_name="persona",
            name="roles",
            field=models.ManyToManyField(blank=True, to="cantovallenato.role"),
        ),
        migrations.CreateModel(
            name="VersionVallenato",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cantovallenato.albumvallenato",
                    ),
                ),
                (
                    "cancion",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cantovallenato.cantovallenato",
                    ),
                ),
                (
                    "interprete",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cantovallenato.agrupacionmusical",
                    ),
                ),
            ],
        ),
    ]
